### ISSUE TITLE
Creating a table

### ISSUE THREAD

**Issue by lgedeon** [johnjamesjacoby/wp-term-meta#3]
Are you creating a table in anticipation of the table being created in WP core anyway? You can get similar functionality without a new table. If you have a second, do you mind taking a look at https://github.com/lgedeon/term-meta ?

**Comment by johnjamesjacoby** [comment]
Right. The idea here is to create an experience that's as close to WordPress core would have done already if it were feasible.

I've seen your plugin (and several others like it) and they're great for sticking within the core schema.
